export const audioAssets={
 music:{url:new URL('../../../../assets/audio/music.wav',import.meta.url).href,title:'Menu music',author:'FCU',source:'Original FCU synthesis',license:'Original project audio',licenseUrl:'',edit:'Original 32-note loop rendered to WAV.'},
 click:{url:new URL('../../../../assets/audio/click.wav',import.meta.url).href,title:'Menu button',author:'FCU',source:'Original FCU synthesis',license:'Original project audio',licenseUrl:'',edit:'Original short triangle note rendered to WAV.'},
 kick:{url:new URL('../../../../assets/audio/kick.wav',import.meta.url).href,title:'Deep ball kick',author:'FCU',source:'Original FCU synthesis',license:'Original project audio',licenseUrl:'',edit:'Owner-approved original WAV; unchanged.'},
 whistle:{url:new URL('../../../../assets/audio/whistle.wav',import.meta.url).href,title:'Kickoff whistle',author:'Pablo-F',source:'https://freesound.org/people/Pablo-F/sounds/90743/',license:'CC BY 3.0',licenseUrl:'https://creativecommons.org/licenses/by/3.0/',edit:'0.55-second excerpt of the existing edited recording; short edge fades, unchanged pitch and level.'},
 fulltime:{url:new URL('../../../../assets/audio/fulltime.wav',import.meta.url).href,title:'Full-time whistle',author:'Pablo-F',source:'https://freesound.org/people/Pablo-F/sounds/90743/',license:'CC BY 3.0',licenseUrl:'https://creativecommons.org/licenses/by/3.0/',edit:'Two 0.18-second blasts then one 0.75-second blast, with silent gaps and edge fades; unchanged pitch and level.'},
 cheer:{url:new URL('../../../../assets/audio/cheer.wav',import.meta.url).href,title:'Cheer.wav',author:'Owner-supplied audio',source:'Supplied by the project owner',license:'Source attribution not supplied',licenseUrl:'',edit:'Copied unchanged from Cheer.wav.'},
 groan:{url:new URL('../../../../assets/audio/groan.wav',import.meta.url).href,title:'Missed.wav',author:'Owner-supplied audio',source:'Supplied by the project owner',license:'Source attribution not supplied',licenseUrl:'',edit:'Copied unchanged from Missed.wav.'},
 tackle:{url:new URL('../../../../assets/audio/tackle.wav',import.meta.url).href,title:'Foul whistle',author:'Pablo-F',source:'https://freesound.org/people/Pablo-F/sounds/90743/',license:'CC BY 3.0',licenseUrl:'https://creativecommons.org/licenses/by/3.0/',edit:'0.18-second excerpt replaces grass tackle sound; short edge fades, unchanged pitch and level.'},
 crowd:{url:new URL('../../../../assets/audio/crowd.wav',import.meta.url).href,title:'noise#01.aif',author:'huubjeroen',source:'https://freesound.org/people/huubjeroen/sounds/39733/',license:'CC0 1.0',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',edit:'Public HQ MP3 preview; stadium ambience excerpt, level adjustment and fades.'}
};
