// Presentation colors identify managed/opponent sides, independently of club kits.
export const highlightArt={
 'halftime':new URL('./assets/highlights/halftime.png',import.meta.url).href,
 'blue-win':new URL('./assets/highlights/blue-win.png',import.meta.url).href,
 'red-win':new URL('./assets/highlights/red-win.png',import.meta.url).href,
 'coach':new URL('./assets/highlights/coach.png',import.meta.url).href,
 'blue-foul':new URL('./assets/highlights/blue-foul.png',import.meta.url).href,
 'blue-yellow':new URL('./assets/highlights/blue-yellow.png',import.meta.url).href,
 'blue-red':new URL('./assets/highlights/blue-red.png',import.meta.url).href,
 'blue-warning':new URL('./assets/highlights/blue-warning.png',import.meta.url).href,
 'blue-injury':new URL('./assets/highlights/blue-injury.png',import.meta.url).href,
 'blue-substitution':new URL('./assets/highlights/blue-substitution.png',import.meta.url).href,
 'blue-penalty':new URL('./assets/highlights/blue-penalty.png',import.meta.url).href,
 'blue-penaltyMiss':new URL('./assets/highlights/blue-penaltyMiss.png',import.meta.url).href,
 'red-foul':new URL('./assets/highlights/red-foul.png',import.meta.url).href,
 'red-yellow':new URL('./assets/highlights/red-yellow.png',import.meta.url).href,
 'red-red':new URL('./assets/highlights/red-red.png',import.meta.url).href,
 'red-warning':new URL('./assets/highlights/red-warning.png',import.meta.url).href,
 'red-injury':new URL('./assets/highlights/red-injury.png',import.meta.url).href,
 'red-substitution':new URL('./assets/highlights/red-substitution.png',import.meta.url).href,
 'red-penalty':new URL('./assets/highlights/red-penalty.png',import.meta.url).href,
 'red-penaltyMiss':new URL('./assets/highlights/red-penaltyMiss.png',import.meta.url).href,
 'lineup':new URL('./assets/highlights/lineup.png',import.meta.url).href,
 'blue-prepare':new URL('./assets/highlights/blue-prepare.png',import.meta.url).href,
 'blue-goal':new URL('./assets/highlights/blue-goal.png',import.meta.url).href,
 'blue-save':new URL('./assets/highlights/blue-save.png',import.meta.url).href,
 'blue-miss':new URL('./assets/highlights/blue-miss.png',import.meta.url).href,
 'red-prepare':new URL('./assets/highlights/red-prepare.png',import.meta.url).href,
 'red-goal':new URL('./assets/highlights/red-goal.png',import.meta.url).href,
 'red-save':new URL('./assets/highlights/red-save.png',import.meta.url).href,
 'red-miss':new URL('./assets/highlights/red-miss.png',import.meta.url).href,
};
