import type { Career } from '../../../../packages/contracts/src/index.ts';
import { text as t, describeEvent } from '../../../../packages/presentation/src/text.ts';
import { ClubBadge } from './GameArt.tsx';
import { MatchVisual } from './MatchVisual.tsx';
import s from './App.module.css';
export function MatchScreen({state,busy,playing,speed,play,continuousHalf,changeContinuous,changeSpeed,done,goal}:{state:Career;busy:boolean;playing:boolean;speed:number;play:()=>void;continuousHalf:boolean;changeContinuous:(value:boolean)=>void;changeSpeed:(speed:number)=>void;done:()=>void;goal:(kind:'goal'|'save'|'shot')=>void}) {
  const match=state.match!;const home=state.clubs.find(c=>c.id===match.home)!;const away=state.clubs.find(c=>c.id===match.away)!;
  return <section className={s.matchScreen}>
    <div className={s.scoreboard}><div className={s.teamName}><ClubBadge color={home.color} short={home.short}/><h2>{home.name}</h2></div><div className={s.score}><span className={s.broadcast}>{t.broadcast}</span><strong data-testid="score">{match.homeGoals} - {match.awayGoals}</strong><span data-testid="minute">{match.tick===90?t.fullTime:match.tick===45?t.halfTime:`${match.tick}'`}</span></div><div className={s.teamName}><h2>{away.name}</h2><ClubBadge color={away.color} short={away.short}/></div></div>
    <div className={s.matchBody}><MatchVisual state={state} playing={playing} speed={speed} onGoal={goal}/><aside className={s.broadcastPanel}><h3>{t.events}</h3><ol>{match.events.length===0?<li>{t.noEvents}</li>:[...match.events].filter(e=>e.type!=='pass').reverse().map(e=><li key={e.order} className={e.type==='goal'?s.goalLine:undefined}>{describeEvent(state,e)}</li>)}</ol><div className={s.matchStats}>{([['shots',t.shots],['onTarget',t.onTarget],['possession',t.possession],['quality',t.quality]] as const).map(([key,label])=>{const format=(n:number)=>key==='quality'?(n/10000).toFixed(2):key==='possession'?`${match.tick?Math.round(n/match.tick/100):50}%`:n;return <div key={key}><b>{format(match.homeStats[key])}</b><span>{label}</span><b>{format(match.awayStats[key])}</b></div>;})}</div></aside></div>
    <div className={s.matchControls}>{match.tick<90?<><div className={s.playControls}><button className={s.primary} disabled={busy} onClick={play}>{playing?t.pause:match.tick===45?t.continue:t.play}</button><label><input type="checkbox" checked={continuousHalf} onChange={event=>changeContinuous(event.target.checked)}/>{t.continuousHalf}</label></div><div className={s.speedControls} role="group" aria-label={t.speed}>{([1,2,3] as const).map(value=><button key={value} aria-pressed={speed===value} onClick={()=>changeSpeed(value)}><strong>{value}x</strong><small>{t.speedLabels[value]}</small></button>)}</div></>:<button className={s.primary} onClick={done}>{t.continue} <span aria-hidden="true">▶</span></button>}</div>
  </section>;
}
