import {useState,type ReactNode} from 'react';
import type {Career} from '../../../../packages/contracts/src/index.ts';
import {boundaryArt,highlightFrame,matchMinute,type HighlightKind,type HighlightFrame,type HighlightSide} from '../../../../packages/presentation/src/highlights.ts';
import type {useMatchBroadcast} from './useMatchBroadcast.ts';
import {highlightArt} from './highlightArt.ts';
import {text as t,describeEvent} from '../../../../packages/presentation/src/text.ts';
import s from './MatchVisual.module.css';
export function MatchVisual({state,playing,broadcast,statistics}:{state:Career;playing:boolean;broadcast:ReturnType<typeof useMatchBroadcast>;statistics:ReactNode}){
 const [previewSide,setPreviewSide]=useState<HighlightSide>('blue');
 const [extraScene,setExtraScene]=useState<HighlightKind>('foul');
 const {scene,suspense,failed}=broadcast;const match=state.match!;const event=match.events.at(-1);
 const artKey=(frame:HighlightFrame,side:HighlightSide)=>frame==='coach'||frame==='lineup'||frame==='halftime'?frame:side+'-'+(frame==='tackle'?'foul':frame==='foul'?'warning':frame==='shot'?'miss':frame);
 const frame=scene?.frame;const selected=scene?artKey(scene.frame,scene.highlight.side):boundaryArt(state);
 const needed=new Set([selected,...(scene?[artKey(highlightFrame(scene.highlight.kind,1),scene.highlight.side)]:[])]);
 const alt=(key:string)=>{const kind=key==='lineup'?'lineup':key==='coach'?'coach':key==='halftime'?'halftime':key.slice(key.indexOf('-')+1);return kind==='lineup'?t.lineupArt:kind in t.stillAlt?t.stillAlt[kind as keyof typeof t.stillAlt]:kind==='warning'?t.sceneAlt.foul:kind==='foul'?t.sceneAlt.tackle:t.sceneAlt[kind as keyof typeof t.sceneAlt];};
 const caption=frame==='prepare'?(scene?.highlight.side==='blue'?t.yourChance:t.theirChance):frame?t.sceneTitle[frame]:match.tick===0?t.beforeKickoff:match.phase==='finished'?t.fullTime:match.phase==='interval'||match.phase==='extraInterval'?t.halfTime:t.ballInPlay;
  const recent=suspense?caption:event&&event.tick===match.tick?describeEvent(state,event):match.tick===0?t.noEvents:match.phase==='finished'?t.fullTime:playing?t.noChance:t.paused;
  return <section className={s.visual}>
    <div className={s.stage}>
      <div className={s.highlight} role="region" aria-label={t.highlights}><div className={s.picture}>{!failed?Object.entries(highlightArt).filter(([key])=>needed.has(key)).map(([key,src])=><img key={key} src={src} width={1672} height={941} hidden={key!==selected} alt={alt(key)} onError={broadcast.fail}/>):<p className={s.notice}>{t.artFailed}</p>}{!failed&&!selected&&<div className={s.quiet}><strong>{playing?t.ballInPlay:t.paused}</strong><p>{t.watchForChance}</p><div><span>{t.blueSide}</span><span>{t.redSide}</span></div></div>}</div><div className={s.clipLabel}><span><strong>{caption}</strong><small>{scene?scene.preview?t.previewNote:(scene.highlight.side==='blue'?t.blueSide:t.redSide)+' / '+scene.highlight.player:t.highlightIllustration}</small></span>{scene&&<button onClick={broadcast.skip}>{t.skipHighlight}</button>}</div></div>
      <aside className={s.analysis}><div className={s.commentary}><header className={s.toolbar}><strong>{t.events}</strong><span>{match.phase==='finished'?t.fullTime:playing?t.live:t.paused}</span></header><p className={s.lead} aria-live="polite">{(!event||event.tick!==match.tick)&&<span>{matchMinute(match.tick,match.addedTime[0]??0,match.addedTime[1]??0,match.extraTime)}'</span>}{recent}</p><ol aria-label={t.events}>{match.penalties.map((kick,i)=><li key={'penalty-'+i}>{t.penalties} {i+1}: {state.players.find(p=>p.id===kick.playerId)!.name} / {kick.scored?t.penaltyScored:t.penaltyMissed}</li>)}{[...match.events].filter(e=>e.type!=='pass').reverse().map(e=><li key={e.order} className={e.type==='goal'?s.goal:e.type==='yellow'?s.yellow:e.type==='red'||e.type==='secondYellow'||e.type==='injury'?s.incident:undefined}>{describeEvent(state,e)}</li>)}</ol></div>{statistics}</aside>
    </div>
    {!failed&&<details className={s.previews}><summary>{t.artPreview}</summary><div role="group" aria-label={t.artPreview}><label>{t.previewSide}<select disabled={playing} value={previewSide} onChange={e=>setPreviewSide(e.target.value as HighlightSide)}><option value="blue">{t.blueSide}</option><option value="red">{t.redSide}</option></select></label><button disabled={playing} onClick={()=>broadcast.preview('goal',previewSide)}>{t.previewGoal}</button><button disabled={playing} onClick={()=>broadcast.preview('save',previewSide)}>{t.previewSave}</button><button disabled={playing} onClick={()=>broadcast.preview('shot',previewSide)}>{t.previewMiss}</button></div><div><label>{t.additionalScenes}<select disabled={playing} value={extraScene} onChange={e=>setExtraScene(e.target.value as HighlightKind)}>{Object.entries(t.extraScene).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button disabled={playing} onClick={()=>broadcast.preview(extraScene,previewSide)}>{t.previewScene}</button></div></details>}
  </section>;
}
