import {loanEnd} from '../../../../packages/simulation/src/loans.ts';
import {useState} from 'react';
import type {Career,Command,Player,Contract} from '../../../../packages/contracts/src/index.ts';
import {askingPrice,activeOffer,dealError,nextWindow,windowOpen} from '../../../../packages/simulation/src/market.ts';
import {desiredTerms,contractEnd} from '../../../../packages/simulation/src/contracts.ts';
import {budgets} from '../../../../packages/simulation/src/economy.ts';
import {money,parseEuro} from '../../../../packages/presentation/src/money.ts';
import {text as t} from '../../../../packages/presentation/src/text.ts';
import s from './ContractsMenu.module.css';
type Payload<T>=T extends Command?Omit<T,'careerId'|'commandId'|'expectedRevision'>:never;
export type MarketAction=Payload<Extract<Command,{type:'SubmitLoan'|'SubmitOffer'|'CounterOffer'|'AcceptOffer'|'OfferTerms'|'ConfirmDeal'|'WithdrawOffer'}>>;
export function OfferPanel({state,player,busy,command}:{state:Career;player:Player;busy:boolean;command:(action:MarketAction)=>Promise<boolean>}){
 const offer=state.offers.filter(o=>o.playerId===player.id&&o.buyerId===state.clubId).at(-1);
 const [kind,setKind]=useState('transfer'),[share,setShare]=useState<0|50|100>(100);
 const loan=offer?.loanShare!==null&&offer?.loanShare!==undefined,registeredLoan=state.loans.find(l=>l.playerId===player.id&&l.status==='active'),returned=offer&&state.loans.some(l=>l.id===offer.id&&l.status==='returned');
 const [fee,setFee]=useState(String(askingPrice(state,player)/100)),[wage,setWage]=useState(String(desiredTerms(state,player).wage/100)),[years,setYears]=useState(2),[role,setRole]=useState<Contract['role']>(state.contracts[player.id]!.role);
 const cents=parseEuro(fee),salary=parseEuro(wage),bank=budgets(state,state.clubId);
 const terms=loan?{years:1,wage:state.economy.wages[player.id]!,bonus:0,role:state.contracts[player.id]!.role}:{years,wage:salary??0,bonus:4*(salary??0),role};
 const weekly=offer?.terms?bank.committed+(loan?Math.floor(offer.terms.wage*offer.loanShare!/100):offer.terms.wage):bank.committed;
 const starts=offer?.sellerId!==null&&!windowOpen(state.date)?nextWindow(state.date):state.date;
 const error=offer&&offer.status==='accepted'?(salary===null?'PLAYER_TERMS':dealError(state,{...offer,terms})):offer?.status==='ready'?dealError(state,offer):null;
 return <><h3>{player.name}</h3>{!loan&&kind!=='loan'&&<p>{t.askingPrice}: {money(askingPrice(state,player))}</p>}{registeredLoan&&<p>{t.loanUntil}: {registeredLoan.ends}</p>}
 {offer&&<div className={s.review} role="status"><strong>{t.offerStatuses[offer.status]}</strong><span>{offer.reason?t.offerReasons[offer.reason]:offer.status==='completed'?(returned?t.loanReturned:loan?t.loanSigned:t.signedHint):offer.status==='queued'?`${t.queuedHint} ${offer.activation}`:`${t.expires}: ${offer.expires}`}</span></div>}
 {(!offer||!activeOffer(offer))&&player.clubId!==state.clubId&&!registeredLoan&&state.date<'2027-06-30'&&<>{player.clubId!==null&&<label>{t.dealType}<select value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}><option value="transfer">{t.permanentTransfer}</option><option value="loan">{t.loan}</option></select></label>}{kind==='loan'&&player.clubId!==null?<><label>{t.wageShare}<select disabled={busy} value={share} onChange={e=>setShare(Number(e.target.value) as 0|50|100)}>{[0,50,100].map(n=><option key={n} value={n}>{n}%</option>)}</select></label><p>{t.loanUntil}: {loanEnd(starts)}</p><button disabled={busy} onClick={()=>void command({type:'SubmitLoan',playerId:player.id,share})}>{t.requestLoan}</button></>:<><label>{t.offerFee}<input disabled={busy||player.clubId===null} inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)}/></label><button disabled={busy||cents===null} onClick={()=>void command({type:'SubmitOffer',playerId:player.id,fee:cents??0})}>{player.clubId===null?t.startTerms:t.submitOffer}</button></>}</>}
 {offer?.status==='submitted'&&<p>{t.responds}: {offer.responseDate}</p>}
 {offer?.status==='countered'&&<><p>{t.transferFee}: {money(offer.fee)}</p><button disabled={busy} onClick={()=>void command({type:'AcceptOffer',offerId:offer.id})}>{t.acceptFee}</button>{offer.buyerCounters<2&&<><label>{t.offerFee}<input disabled={busy} inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)}/></label><button disabled={busy||cents===null} onClick={()=>void command({type:'CounterOffer',offerId:offer.id,fee:cents??0})}>{t.counterOffer}</button></>}</>}
 {offer?.status==='accepted'&&<>{loan?<p>{t.wageShare}: {offer.loanShare}% / {money(Math.floor(terms.wage*offer.loanShare!/100))} / {t.loanUntil}: {loanEnd(starts)}</p>:<div className={s.fields}><label>{t.weeklyOffer}<input disabled={busy} inputMode="decimal" value={wage} onChange={e=>setWage(e.target.value)}/></label><label>{t.contractYears}<select disabled={busy} value={years} onChange={e=>setYears(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / {contractEnd(state.date,n)}</option>)}</select></label><label>{t.promisedRole}<select disabled={busy} value={role} onChange={e=>setRole(e.target.value as Contract['role'])}>{(['starter','rotation','prospect'] as const).map(r=><option key={r} value={r}>{t.contractRoles[r]}</option>)}</select></label></div>}<p>{t.signingBonus}: {money(terms.bonus)}</p><button disabled={busy||!!error} onClick={()=>void command({type:'OfferTerms',offerId:offer.id,terms})}>{t.reviewDeal}</button></>}
 {offer?.status==='ready'&&<>{loan&&<strong>{t.loan} / {t.wageShare}: {offer.loanShare}% / {money(Math.floor(offer.terms!.wage*offer.loanShare!/100))}</strong>}<div className={s.review}><p>{t.transferFee}<b>{money(offer.fee)}</b></p><p>{t.signingBonus}<b>{money(offer.terms!.bonus)}</b></p><p>{t.weeklyWages}<b>{money(weekly)} / {money(bank.wage)}</b></p><p>{t.cashAfter}<b>{money(bank.cash-offer.fee-offer.terms!.bonus)}</b></p><p>{t.reservedCash}<b>{money(13*(weekly)+4*bank.overhead)}</b></p><p>{loan?t.loanUntil:t.contractUntil}<b>{loan?loanEnd(starts):contractEnd(starts,offer.terms!.years)}</b></p><p>{t.promisedRole}<b>{t.contractRoles[offer.terms!.role]}</b></p></div>{offer.sellerId!==null&&!windowOpen(state.date)&&<p>{t.queuedHint} {nextWindow(state.date)}</p>}<button disabled={busy||!!error} onClick={()=>void command({type:'ConfirmDeal',offerId:offer.id})}>{t.confirmDeal}</button></>}
 {error&&<p role="status">{t.errors[error]}</p>}
 {offer&&activeOffer(offer)&&<button disabled={busy} onClick={()=>void command({type:'WithdrawOffer',offerId:offer.id})}>{t.withdrawOffer}</button>}
 {state.date>='2027-06-30'&&<p>{t.calendarClosed}</p>}<p>{loan||kind==='loan'?t.loanHint:t.transferHint}</p></>;
}
