import {CupBoard} from './CupBoard.tsx';
import {selectionPlayers} from '../../../../packages/simulation/src/discipline.ts';
import {useState} from 'react';
import {worldClubs,countryWorld} from '../../../../packages/contracts/src/world.ts';
import {seasonEnd,nextManagedFixture,divisionFor,seasonComplete} from '../../../../packages/simulation/src/competition.ts';
import {MarketNews} from './MarketNews.tsx';
import {nextFixtureDate,nextCalendarDate} from '../../../../packages/simulation/src/calendar.ts';
import {available} from '../../../../packages/simulation/src/availability.ts';
import type { InstalledRoster, Career, ClubId, PlayerId } from '../../../../packages/contracts/src/index.ts';
import { brand } from '../../../../packages/contracts/src/index.ts';
import { clubs } from '../../../../packages/contracts/src/identity.ts';
import { overall, standings, requiresCallUp, arrangeLineup, validLineup } from '../../../../packages/simulation/src/engine.ts';
import { text as t } from '../../../../packages/presentation/src/text.ts';
import { ClubBadge, Shirt, StadiumArt } from './GameArt.tsx';
import s from './App.module.css';

export function TitleScreen({start,load,resume}:{start:()=>void;load:()=>void;resume:(()=>void)|null}) {
  return <section className={s.titleScene}>
    <div className={s.titleGlow}/><StadiumArt/>
    <div className={s.titleContent}><p className={s.eyebrow}>{t.retroMode}</p><h1 className={s.titleLogo}>{brand.short}<span>{brand.title}</span></h1><p className={s.tagline}>{t.titleTag}</p>
      <div className={s.titleButtons}><button className={s.primary} onClick={start}><span aria-hidden="true">▶</span> {t.startGame}</button><button onClick={load}>{t.load}</button>{resume&&<button onClick={resume}>{t.continue}</button>}</div>
    </div><p className={s.titleFoot}>{t.gameNote}</p>
  </section>;
}
export function ClubSelect({packs,packId,changePack,importPack,importedClubs,club,worldKind,changeWorld,seed,changeClub,changeSeed,begin,busy}:{packs:InstalledRoster[];packId:string;changePack:(id:string)=>void;importPack:()=>void;importedClubs:Career['clubs']|null;club:ClubId;worldKind:Career['world']['kind'];changeWorld:(kind:Career['world']['kind'])=>void;seed:string;changeClub:(id:ClubId)=>void;changeSeed:(seed:string)=>void;begin:()=>void;busy:boolean}) {
  const identities=worldKind==='countries'?worldClubs.map(c=>importedClubs?.find(t=>t.id===c.id)??c):clubs;const selected=identities.find(c=>c.id===club)!;const division=countryWorld.divisions.find(d=>d.clubs.includes(club));const choices=worldKind==='countries'?identities.filter(c=>division!.clubs.includes(c.id)):clubs;
  return <section className={s.selectionScreen}>
    <div className={s.sectionTitle}><p className={s.eyebrow}>{brand.career}</p><h1>{t.chooseClub}</h1><div className={s.worldChoices}><label>{t.rosterVersion}<select disabled={busy} value={packId} onChange={e=>changePack(e.target.value)}><option value="">{t.bundledRoster}</option>{packs.map(p=><option key={p.snapshotId} value={p.snapshotId}>{p.snapshotId}{p.development?` / ${t.developmentRoster}`:""}</option>)}</select></label><button disabled={busy} onClick={importPack}>{t.importRoster}</button>{packId&&<small>{t.rosterPinned} / {packs.find(p=>p.snapshotId===packId)?.observedAt.slice(0,10)}</small>}</div><div className={s.worldChoices}><button disabled={busy} aria-pressed={worldKind==='countries'} onClick={()=>changeWorld('countries')}>{t.countryCareer}</button><button disabled={busy} aria-pressed={worldKind==='exhibition'} onClick={()=>changeWorld('exhibition')}>{t.compactExhibition}</button>{worldKind==='countries'&&<><label>{t.country}<select aria-label={t.country} disabled={busy} value={division!.country} onChange={e=>changeClub(countryWorld.divisions.find(d=>d.country===e.target.value&&d.tier===division!.tier)!.clubs[0]!)}>{(['ENG','ESP','FRA','ITA','DEU'] as const).map(c=><option key={c} value={c}>{t.countries[c]}</option>)}</select></label><label>{t.division}<select aria-label={t.division} disabled={busy} value={division!.tier} onChange={e=>changeClub(countryWorld.divisions.find(d=>d.country===division!.country&&d.tier===Number(e.target.value))!.clubs[0]!)}><option value="1">{t.topDivision}</option><option value="2">{t.secondDivision}</option></select></label></>}</div></div>
    <div className={s.selectBody}><div className={s.clubGrid} role="group" aria-label={t.club}>{choices.map(c=><button key={c.id} aria-pressed={c.id===club} onClick={()=>changeClub(c.id)} disabled={busy}><ClubBadge color={c.color} short={c.short}/><strong>{c.name}</strong></button>)}</div>
      <div className={s.clubPreview}><Shirt color={selected.color}/><h2>{selected.name}</h2><p>{packId?t.registrationHint:t.rosterShort} / {t.profile}</p><label>{t.seed}<input inputMode="numeric" value={seed} onChange={e=>changeSeed(e.target.value)} disabled={busy}/></label><button className={s.primary} onClick={begin} disabled={busy}>{t.begin} <span aria-hidden="true">▶</span></button></div>
    </div><p className={s.smallPrint}>{worldKind==='countries'?t.worldNotice:t.fixtureNotice}</p>
  </section>;
}
export function Clubhouse({state,closeSeason,history,news,scouting,advance,finance,report,squad,table,match,busy}:{state:Career;closeSeason:()=>void;history:()=>void;news:(id:PlayerId)=>void;scouting:()=>void;advance:(target:'day'|'event')=>void;finance:()=>void;report:()=>void;squad:()=>void;table:()=>void;match:()=>void;busy:boolean}) {
  const club=state.clubs.find(c=>c.id===state.clubId)!;const rankings=standings(state);const row=rankings.find(r=>r.clubId===state.clubId)!;
  const next=nextManagedFixture(state),division=divisionFor(state),total=2*(division.clubs.length-1);
  const name=(id:ClubId)=>state.clubs.find(c=>c.id===id)!;
  const date=nextFixtureDate(state);const matchDay=date===state.date;const canAdvance=!!nextCalendarDate(state)&&(!next||!matchDay);
  return <section className={s.clubhouse}>
    <div className={s.clubHero}><ClubBadge color={club.color} short={club.short}/><div><p className={s.eyebrow}>{brand.career} / {t.clubhouse}</p><h1>{club.name}</h1><p>{state.world.kind==='countries'?`${t.countries[division.country]} / ${division.tier===1?t.topDivision:t.secondDivision}`:t.seasonTag} / {state.season}-{state.season+1} <span>/</span> <time data-testid="career-date" dateTime={state.date}>{state.date}</time></p></div><div className={s.rankStamp}><strong>#{rankings.findIndex(r=>r.clubId===club.id)+1}</strong><small>{t.currentPosition}</small></div></div>
    <div className={s.clubhouseBody}><section className={s.fixtureBoard}><p className={s.eyebrow}>{next?t.nextFixture:seasonComplete(state)?t.seasonComplete:t.campaignComplete}</p>{next?<><div className={s.versus}><div><ClubBadge color={name(next.home).color} short={name(next.home).short}/><strong>{name(next.home).name}</strong></div><b>{t.versus}</b><div><ClubBadge color={name(next.away).color} short={name(next.away).short}/><strong>{name(next.away).name}</strong></div></div><p>{next.competitionClass==='league'?`${t.round} ${next.round+1} / ${total}`:t.cupNames[next.competitionId as keyof typeof t.cupNames]} / {t.fixtureDate}: {date}</p><button disabled={busy} className={s.primary} onClick={matchDay?match:()=>advance('event')}>{state.match&&state.match.phase!=='finished'?t.continue:matchDay?t.kickoff:t.nextEvent} <span aria-hidden="true">▶</span></button></>:<><div className={s.trophy} aria-hidden="true">★</div><h2>{name(rankings[0]!.clubId).name}</h2><p>{t.seasonBody}</p>{state.date===seasonEnd(state.season)&&seasonComplete(state)&&<><p>{t.closeSeasonHint}</p><button className={s.primary} disabled={busy} onClick={closeSeason}>{t.nextSeason}</button></>}</>}{canAdvance&&<button disabled={busy} onClick={()=>advance(next?'day':'event')}>{next?t.nextDay:t.nextEvent}</button>}{state.scouting.active&&<p>{t.scoutDue}: {state.scouting.active.due}</p>}<MarketNews state={state} open={news}/></section>
      <div className={s.actionTiles}><button aria-label={t.squad} onClick={squad}><span className={s.tileIcon} aria-hidden="true">XI</span><span><strong>{t.squad}</strong><small>{t.squadAction}</small></span><b aria-hidden="true">›</b></button><button aria-label={t.table} onClick={table}><span className={s.tileIcon} aria-hidden="true">★</span><span><strong>{t.table}</strong><small>{t.tableAction}</small></span><b aria-hidden="true">›</b></button><button aria-label={t.finances} onClick={finance}><span className={s.tileIcon} aria-hidden="true">EUR</span><span><strong>{t.finances}</strong><small>{t.financeAction}</small></span></button><button aria-label={t.scouting} onClick={scouting}><span className={s.tileIcon} aria-hidden="true">?</span><span><strong>{t.scouting}</strong><small>{t.scoutingAction}</small></span></button><div className={s.seasonNumbers}><div><b>{row.won}-{row.drawn}-{row.lost}</b><small>{t.record}</small></div><div><b>{row.played}/{total}</b><small>{t.playedRounds}</small></div><div><b>{row.points}</b><small>{t.points}</small></div></div>{state.history.length>0&&<button className={s.wideAction} onClick={history}>{t.seasonHistory}</button>}{state.match?.phase==='finished'&&<button className={s.wideAction} onClick={report}>{t.lastResult} / {t.matchReport}</button>}</div>
    </div>
  </section>;
}
export function SquadScreen({state,registration,contracts,forfeit,callUp,training,bench,tactics,lineup,change,suggest,confirm,busy}:{state:Career;registration:()=>void;contracts:()=>void;forfeit:()=>void;callUp:()=>void;training:(value:Career['training'])=>void;bench:()=>void;tactics:()=>void;lineup:PlayerId[];change:(ids:PlayerId[])=>void;suggest:()=>void;confirm:()=>void;busy:boolean}) {
  const players=selectionPlayers(state).filter(p=>p.clubId===state.clubId);const club=state.clubs.find(c=>c.id===state.clubId)!;const locked=busy||Boolean(state.match&&state.match.phase!=='finished');
  const slots=validLineup(state.players,state.clubId,lineup)?arrangeLineup(state.players,lineup,state.tactics.formation):lineup.map(id=>({role:state.players.find(p=>p.id===id)!.role,player:state.players.find(p=>p.id===id)!}));
  return <section className={s.squadScreen}><div className={s.sectionTitle}><p className={s.eyebrow}>{club.name}</p><h1>{t.squadTitle}</h1><p>{locked?t.matchLocked:t.squadHint}</p></div>
    <div className={s.squadBody}><div data-input-section className={s.squadList}>{players.map(p=><label className={lineup.includes(p.id)?s.picked:undefined} key={p.id}><input type="checkbox" checked={lineup.includes(p.id)} disabled={locked||(!lineup.includes(p.id)&&!available(p,state.date))} aria-label={`${t.starting} ${p.name}`} onChange={e=>change(e.target.checked?[...lineup,p.id]:lineup.filter(id=>id!==p.id))}/><span className={s.role}>{p.role}</span><strong>{p.name}{!p.registered&&<small> / {t.inactivePlayer}</small>}{state.loans.some(l=>l.playerId===p.id&&l.status==='active')&&<small> / {t.loan}</small>}{p.leagueBan>0?<small> / {t.suspended}: {p.leagueBan}</small>:p.injuryUntil&&p.injuryUntil>state.date?<small> / {t.injured} {p.injuryUntil}</small>:null}</strong><b title={t.ability}>{overall(p)}</b><small title={`${t.condition} / ${t.morale}`} aria-label={`${t.condition} ${p.name}`}>{Math.round(p.condition/1000)}% / {p.morale}</small></label>)}</div>
      <div data-input-section className={s.lineupPanel}><p className={s.eyebrow}>{t.starters} / {state.tactics.formation} <button disabled={locked} onClick={tactics}>{t.tactics}</button></p><div className={s.tacticsPitch}>{(['FWD','MID','DEF','GK'] as const).map(role=><div key={role}>{slots.filter(s=>s.role===role).map(({player:p})=><div key={p.id} title={p.name}><span style={{background:club.color}}>{p.id.slice(-2)}</span><small>{p.name.split(' ')[0]}</small></div>)}</div>)}</div><div className={s.training}>{requiresCallUp(state)&&<><p>{t.academyHint}</p><button disabled={locked||players.filter(p=>p.academy).length>=8} onClick={callUp}>{t.callUp}</button>{players.filter(p=>p.academy).length===8&&players.filter(p=>available(p,state.date)).length<7&&<button disabled={locked} onClick={forfeit}>{t.forfeit}</button>}</>}<h3>{t.training}</h3><div role="group" aria-label={t.training}>{(["light","balanced","intense"] as const).map(value=><button key={value} disabled={busy} aria-pressed={state.training===value} onClick={()=>training(value)}>{t.trainingChoices[value]}</button>)}</div><p>{t.trainingHint}</p></div><div className={s.lineupActions}><strong>{lineup.length}/11 {t.selection}</strong><button disabled={locked} onClick={registration}>{t.registration}</button><button disabled={locked} onClick={contracts}>{t.contracts}</button><button disabled={locked} onClick={bench}>{t.chooseBench}</button><button disabled={locked} onClick={suggest}>{t.autoPick}</button><button className={s.primary} disabled={locked} onClick={confirm}>{t.confirmLineup}</button></div></div>
    </div>
  </section>;
}
export function TableScreen({state}:{state:Career}) {
  const [divisionId,setDivisionId]=useState(divisionFor(state).id);const division=state.world.divisions.find(d=>d.id===divisionId)!;const cup=state.cups.find(c=>c.id===divisionId);const rows=cup?[]:standings(state,divisionId);const name=(id:ClubId)=>state.clubs.find(c=>c.id===id)!;
  return <section className={s.tableScreen}><div className={s.sectionTitle}><p className={s.eyebrow}>{state.season}-{state.season+1}</p><h1>{t.table}</h1><label>{t.division}<select aria-label={t.division} value={divisionId} onChange={e=>setDivisionId(e.target.value)}>{state.world.divisions.map(d=><option key={d.id} value={d.id}>{d.country==='EXH'?t.exhibition:`${t.countries[d.country]} / ${d.tier===1?t.topDivision:t.secondDivision}`}</option>)}{state.cups.map(c=><option key={c.id} value={c.id}>{t.cupNames[c.id]}</option>)}</select></label>{!cup&&<p>{division.clubs.length} {t.clubsCount} / {2*(division.clubs.length-1)} {t.roundsTotal}</p>}</div><div className={s.tableWrap}>{cup?<CupBoard key={cup.id} cup={cup} state={state} fixtures={state.fixtures}/>:<table><thead><tr>{['#',t.clubName,t.played,t.won,t.drawn,t.lost,t.goalsFor,t.goalsAgainst,t.difference,t.points].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.clubId} className={r.clubId===state.clubId?s.selected:undefined}><td>{i+1}</td><td><span className={s.tableClub}><ClubBadge color={name(r.clubId).color} short={name(r.clubId).short}/>{name(r.clubId).name}</span></td><td>{r.played}</td><td>{r.won}</td><td>{r.drawn}</td><td>{r.lost}</td><td>{r.gf}</td><td>{r.ga}</td><td>{r.gf-r.ga}</td><td><strong>{r.points}</strong></td></tr>)}</tbody></table>}</div><p className={s.smallPrint}>{cup?t.cupRules:t.ranking}</p></section>;
}
