import {describe,it,expect} from 'vitest';
import {z} from 'zod';
import {fictionalCandidate} from '../packages/roster-pipeline/src/fictional.ts';
import {candidate,approve,canonicalRoster,rosterChanges} from '../packages/roster-pipeline/src/review.ts';
import {validateRoster} from '../packages/roster-pipeline/src/validate.ts';
import {collectPages} from '../packages/roster-pipeline/src/provider.ts';
import {generateKeyPairSync} from 'node:crypto';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {zipSync,unzipSync,strToU8} from 'fflate';
import {createArchive,openArchive} from '../packages/roster-pipeline/src/archive.ts';
import {writeArchive} from '../packages/roster-pipeline/src/store.ts';
import {createPackedCareer,rosterClubs} from '../packages/simulation/src/roster.ts';
import {createSaveStore} from '../apps/game/src/main/saves.ts';

describe('Publisher roster boundaries',()=>{
  it('preserves Unicode and stable identity through reordered snapshots and a transfer',async()=>{
    const a=fictionalCandidate(true), b=structuredClone(a);
    b.roster.players[0]!.displayName='Jos\u00e9 M\u00fcller';a.roster.players[0]!.displayName=b.roster.players[0]!.displayName;
    b.roster.players.reverse();b.roster.teams.reverse();b.roster.memberships.reverse();b.roster.gameProfiles.reverse();b.roster.competitions.reverse();b.roster.competitions.forEach(c=>c.participatingTeamIds.reverse());
    expect(canonicalRoster(a.roster)).toBe(canonicalRoster(b.roster));
    const moved=b.roster.memberships.find(m=>m.playerId===a.roster.players[3]!.id)!;
    moved.playingTeamId=a.roster.teams[1]!.id;moved.owningTeamId=moved.playingTeamId;
    expect(validateRoster(b.roster,b.audit).ok).toBe(true);
    expect(rosterChanges(a.roster,b.roster)).toEqual([{kind:'transfer',playerId:moved.playerId,name:a.roster.players[3]!.displayName,from:a.roster.teams[0]!.id,to:moved.playingTeamId}]);
    expect(a.roster.memberships[3]!.playingTeamId).toBe(a.roster.teams[0]!.id);
    const pack={snapshotId:'roster-2026-27.20260912.r1',contentHash:'a'.repeat(64),observedAt:a.audit.extractionCompletedAt,development:true,roster:a.roster};
    const club=rosterClubs(pack)[0]!.id;
    const career=createPackedCareer('00000000-0000-4000-8000-000000000001',2026,club,pack);
    const saves=createSaveStore(await mkdtemp(join(tmpdir(),'fcu-import-career-')));const commit=await saves.save(career,'manual');
    const loaded=await saves.load(career.careerId,commit);expect(loaded).toEqual(career);expect(loaded.players.some(p=>p.name==='Jos\u00e9 M\u00fcller')).toBe(true);
    const changed=createPackedCareer('00000000-0000-4000-8000-000000000002',2026,club,{...pack,snapshotId:'roster-2026-27.20260912.r2',roster:b.roster});
    const originalId=Object.entries(career.rosterOrigin!.playerIds).find(([,source])=>source===moved.playerId)![0];
    const changedId=Object.entries(changed.rosterOrigin!.playerIds).find(([,source])=>source===moved.playerId)![0];
    expect(career.players.find(p=>p.id===originalId)!.clubId).not.toBe(changed.players.find(p=>p.id===changedId)!.clubId);
    expect(await saves.load(career.careerId,commit)).toEqual(career);
  });
  it('blocks incomplete coverage, unresolved identities and malformed roster facts',()=>{
    const input=fictionalCandidate();
    expect(validateRoster(input.roster,input.audit)).toMatchObject({ok:false,issues:expect.arrayContaining([expect.objectContaining({code:'REVIEW_REQUIRED'})])});
    input.audit.reviewedTeamIds=[...input.audit.completedTeamIds];input.audit.completedTeamIds.pop();input.audit.unresolvedIdentities.push('ambiguous-person');input.roster.memberships.push({...input.roster.memberships[0]!});
    const result=validateRoster(input.roster,input.audit);expect(result.ok).toBe(false);
    if(result.ok)throw Error('Expected blocked roster');
    expect(result.issues.map(i=>i.code)).toEqual(expect.arrayContaining(['INCOMPLETE_FETCH','IDENTITY_CONFLICT','DUPLICATE_ID']));
    input.roster.players[0]!.dateOfBirth='2000-02-30';expect(validateRoster(input.roster,input.audit)).toMatchObject({ok:false,issues:[{code:'INVALID_SCHEMA',entity:null,message:expect.any(String)}]});
  });
  it('finishes pagination and rejects lost pages, duplicate IDs and cursor cycles',async()=>{
    const stamp='2026-09-12T12:00:00Z';const item=z.strictObject({id:z.string()});
    const page=(ids:string[],cursor:string|null,fingerprint:string,total=2)=>({items:ids.map(id=>({id})),nextCursor:cursor,total,requestFingerprint:fingerprint,fetchedAtUTC:stamp,sourceUpdatedAtUTC:null});
    const complete=await collectPages(async cursor=>cursor===null?page(['a'],'2','first'):page(['b'],null,'second'),item,x=>x.id);
    expect(complete.items.map(x=>x.id)).toEqual(['a','b']);
    await expect(collectPages(async()=>page(['a'],null,'first'),item,x=>x.id)).rejects.toThrow('INCOMPLETE_FETCH');
    await expect(collectPages(async cursor=>cursor===null?page(['a'],'2','first'):page(['a'],null,'second'),item,x=>x.id)).rejects.toThrow('DUPLICATE_PROVIDER_ID');
    await expect(collectPages(async cursor=>cursor===null?page(['a'],'2','first'):page(['b'],'2','second'),item,x=>x.id)).rejects.toThrow('REPEATED_OR_EMPTY_PAGE');
    await expect(collectPages(async()=>page(['a'],null,'first'),item,x=>x.id,AbortSignal.abort())).rejects.toThrow();
  });
  it('invalidates an exact review on roster or audit edits while content ignores fetch time',()=>{
    const input=fictionalCandidate(true);const before=candidate(input.roster,input.audit);if(!before.ok)throw Error('Invalid fixture');
    const accepted=approve(input.roster,input.audit,before.reviewHash,'Fixture reviewer','2026-09-12T13:00:00Z');expect(accepted.reviewHash).toBe(before.reviewHash);
    input.audit.extractionCompletedAt='2026-09-12T12:05:00Z';const after=candidate(input.roster,input.audit);if(!after.ok)throw Error('Invalid changed fixture');
    expect(after.contentHash).toBe(before.contentHash);expect(after.reviewHash).not.toBe(before.reviewHash);
    expect(()=>approve(input.roster,input.audit,before.reviewHash,'Fixture reviewer','2026-09-12T13:00:00Z')).toThrow('CANDIDATE_CHANGED_OR_INVALID');
    input.roster.gameProfiles[0]!.attributes.shooting++;
    expect(()=>approve(input.roster,input.audit,after.reviewHash,'Fixture reviewer','2026-09-12T13:00:00Z')).toThrow('CANDIDATE_CHANGED_OR_INVALID');
  });
  it('verifies signed immutable packs and refuses tampering, links and unsafe entries',async()=>{
    const input=fictionalCandidate(true), current=candidate(input.roster,input.audit);if(!current.ok)throw Error('Invalid fixture');
    const approval=approve(input.roster,input.audit,current.reviewHash,'Fixture reviewer','2026-09-12T13:00:00Z');
    const keys=generateKeyPairSync('ed25519');const trust={allowDevelopment:false,trustedKeys:new Map([['fixture-key',keys.publicKey]])};
    const options={snapshotId:'roster-2026-27.20260912.r1',previousSnapshotId:null,attribution:'FCU development fixture',rightsRef:null,notices:'Original synthetic fixture.',key:{id:'fixture-key',privateKey:keys.privateKey}};
    const bytes=createArchive(input.roster,input.audit,approval,options);
    expect(openArchive(bytes,trust).roster.players).toHaveLength(2112);
    expect(()=>openArchive(bytes,{...trust,trustedKeys:new Map()})).toThrow('UNTRUSTED_PACK');
    const files=unzipSync(bytes);files['notices.txt']=strToU8('changed');expect(()=>openArchive(zipSync(files),trust)).toThrow('PACK_CHECKSUM');
    const unsafe:Record<string,Uint8Array>={...unzipSync(bytes),'../roster.json':strToU8('{}')};delete unsafe['roster.json'];expect(()=>openArchive(zipSync(unsafe),trust)).toThrow('UNEXPECTED_PACK_ENTRY');
    const symlink=bytes.slice();const data=new DataView(symlink.buffer);let offset=symlink.length-22;offset=data.getUint32(offset+16,true);data.setUint32(offset+38,0xa0000000,true);expect(()=>openArchive(symlink,trust)).toThrow('UNEXPECTED_PACK_ENTRY');
    const development=createArchive(input.roster,input.audit,approval,{...options,key:null});expect(()=>openArchive(development,trust)).toThrow('UNTRUSTED_PACK');expect(openArchive(development,{...trust,allowDevelopment:true}).manifest.permittedDistribution).toBe('development');
    const directory=await mkdtemp(join(tmpdir(),'fcu-roster-pack-'));const path=await writeArchive(directory,bytes,trust);
    await expect(writeArchive(directory,bytes,trust)).rejects.toMatchObject({code:'EEXIST'});expect(await readFile(path)).toEqual(Buffer.from(bytes));
  });
});
